
server:
  port: 5008

spring:
  application:
    name: seat-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_seat
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-service-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true