server:
  port: 5006

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_payment
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

razorpay:
  api:
    key: rzp_test_XXXXXXXXXXXXXXXX  # dashboard se lo
    secret: XXXXXXXXXXXXXXXXXXXXXX
  callback:
    base-url: http://localhost:5006  # port 5006 match!

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true